### ISSUE TITLE
Particle Product Endpoints

### ISSUE THREAD

**Issue by TechplexEngineer** [chuank/node-red-contrib-particle#12]
Greetings,

Thanks for maintaining the particle nodes! 
I started using your nodes and have added particle product endpoint support via the [particle-api-js](https://github.com/particle-iot/particle-api-js) SDK

It is a pretty major change, I have [forked your repo here](https://github.com/TechplexEngineer/node-red-contrib-particle)

Thus far I've partially implemented the subscribe functionality. I haven't done the work to allow dynamically updating the event/deviceid.

I am curious if you might be interested in merging these changes (when complete) and what stipulations you might request.

Thanks for your consideration!

**Comment by chuank** [comment]
Hi there @TechplexEngineer,

Thanks for getting in touch. The `particle-api-js` SDK has grown quite a bit since I started maintaining the particle nodes. I can see the benefits from using the JS SDK, particularly when considering the possible extended methods made easily available by the SDK.

Here's my suggestion and a 'roadmap'. If you wish to put up your hand for any of these, let me know and I'll put you in as a contributor. Especially since you have already started work to port the subscribe node.

Roadmap:
1. switch to use `particle-api-js` in the current existing nodes, maintaining credentials support & existing features
2. add product endpoint support to current existing nodes
3. introduce a 'Particle Cloud' node that can be used to retrieve secondary information from authenticated user account
4. claiming / unclaiming?

I'm using eslint to format the code, and adopt the 1TBS style (just out of habit). If you submit PRs in the future with a different style, I'll likely merge anyway and do a cleanup commit along with any updates. Moving into the end-year I should have some time to work on this over the next few weeks.

**Comment by chuank** [comment]
#13
