### ISSUE TITLE
Problem with the ParticleFunc

### ISSUE THREAD

**Issue by alfredwonders** [chuank/node-red-contrib-particle#6]
Hi! 
I was trying to use the ParticleFunc and changing the deviceID using the input as it is explained in the documentation. Atfer creating a message with the topic "devid" and the corresponding desiredID as the payload of the message, I figured out that this option is not working properly. So I open the particle.js file in the github and I think I found where is the problem.  Inside the if (validOp) (line 266), it should be included 
       setTimeout(function() {
          particlemodule.emit("callFunc", {});
        }, this.timeoutDelay); 
as it is presented in the correspondent else case.

When I run the node in the regular mode (putting the right deviceID in the configurations of the node), I can see in the system console:
        console.log("(ParticleFunc) Calling function...");
        console.log("\tURL:", url);
        console.log("\tDevice ID:", this.devid);
        console.log("\tFunction Name:", this.fname);
        console.log("\tParameter(s):", this.param);
But when I send the deviceID as a parameter, this does not appear in the console, so I figured out that probably it is missing that part.

Would it be possible to you to correct this as soon as possible? 

Thank you

**Comment by chuank** [comment]
Hi @BrunoAlfredo, I tested sending dynamic Device IDs on my own server and it seems to be working fine.

Have a look at my example flow below, I'm using the inject node to switch Device IDs between 2 different Photons. Both are running the Tinker app:
![image](https://user-images.githubusercontent.com/1781911/42669872-32bfdf40-869b-11e8-9311-9a8a82553a99.png)

Details of the inject payload:
![image](https://user-images.githubusercontent.com/1781911/42669924-70161008-869b-11e8-91c5-20721398a82a.png)

To change device IDs dynamically, enter your Device ID name as the payload (as a string).

The topic should be `devid`.

Give it another go and let me know.

**Comment by alfredwonders** [comment]
Thank you @chuank for the help. I am using the same thing. Look
![capturar](https://user-images.githubusercontent.com/36961934/42693563-72407042-86a7-11e8-87d4-3e3cc10c4f49.PNG)
![capturar2](https://user-images.githubusercontent.com/36961934/42693586-897a36ee-86a7-11e8-85a1-12a0b03aa6f1.PNG)
![capturar3](https://user-images.githubusercontent.com/36961934/42693592-8f8007bc-86a7-11e8-877c-5e24ed9009bc.PNG)
Unless we have slight different implementations of the node.

**Comment by alfredwonders** [comment]
Thanks a lot, I lost a lot of hours with this but I finally found the problem. I thought the inject message that changes the deviceID would cause the flow to continue but it is not true. We need to send another inject message to invoke the function.

**Comment by chuank** [comment]
Sorry you had trouble with it.

The way that node-red structures its payloads make it sensible (in my opinion) to have separate sets of incoming messages for 1) changing device ID, and 2) making actual function calls. This is because msg.payload is interpreted differently, depending on what msg.topic is set to. This is also quite consistently implemented amongst other nodes.

I am not keen on allowing an incoming payload object that simultaneously accepts a `devid` change, _and_ a `function` call, as this would require the user to create a nested object to hold both instructions, which then requires parsing within this node to interpret.

If you want to have that sort of behaviour, design a flow upstream that sends these instructions sequentially, or like in the examples above, have multiple inputs going into the node – one for devid changes, the other for actual function calls, and have them called however you wish. This is more in line with the philosophy of visual patching interfaces, and avoids over-compartmentalising nodes that are harder to troubleshoot because they do too many things within itself.

Perhaps I might be convinced in the future, but not at this time.
